language: generic
sudo:required
services:
    - docker
before_install:
    - docker build  -t mprkatti/docker-react-mpk -f Dockerfile.dev .
script:
    -    docker run -e CI=true mprkatti/docker-react-mpk  npm run test
    
